# Generated by Django 4.1.7 on 2023-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medcard',
            options={'verbose_name': 'Медицинская карта', 'verbose_name_plural': 'Медицинские карты'},
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обращения')),
                ('iin', models.CharField(max_length=12, verbose_name='ИИН', null=True)),
                ('lastname', models.CharField(max_length=20, null=True , verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, default='', verbose_name='Отчество')),
                ('faculty', models.CharField(max_length=30, default='', verbose_name='Факультет')),
                ('group', models.CharField(max_length=30, default='', verbose_name='Группа')),
                ('status', models.CharField(max_length=30, default='', verbose_name='Должность')),
                ('diagnosis', models.TextField(null=True, verbose_name='Диагноз')),
                ('suggestions', models.TextField(default='', verbose_name='Назаначение')),
                ('birthdate', models.DateField(verbose_name='Дата рождения', null=True)),
                ('address', models.CharField(max_length=50, default='', verbose_name='Адрес')),
                ('simptoms', models.TextField(verbose_name='Краткий анамнез', null=True)),
                ('additions', models.TextField(default='', verbose_name='Примечание')),
                ('perv_povt', models.CharField(max_length=10, default='первичный', verbose_name='Первичный или повторный')),
            ],
        ),
    ]
